run_arg:
    - --privileged
    - -e DISPLAY=:0
    - -e TERM=xterm-256color
    - -v /tmp/.X11-unix:/tmp/.X11-unix:ro
    - -v /dev:/dev
    - -p 4000:4000
build_arg:
    - --build-arg UID=1000
    - --build-arg GID=1000
mount_pwd: true
lastexecid: ""
